name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Sempre que algo for enviado para a branch main
  pull_request:
    branches:
      - main  # Para pull requests também

jobs:
  # Job para testes
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  # Job para build e push Docker image
  dockerize:
    runs-on: ubuntu-latest
    needs: test  # Só rodar se o job de teste passar

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t seu_usuario/seu_projeto:latest .
      
      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push seu_usuario/seu_projeto:latest
